CREATE TABLE FOLLOWER 
(
  ID VARCHAR2(20) NOT NULL 
, FOLLOWERID VARCHAR2(20) NOT NULL 
);

COMMENT ON COLUMN FOLLOWER.ID IS 'ÆÈ·Î¿ö id';

COMMENT ON COLUMN FOLLOWER.FOLLOWERID IS 'ÆÈ·ÎÀ× id';
