CREATE TABLE GOODS 
(
  GOODSCODE VARCHAR2(200 BYTE) NOT NULL 
, GOODSTITLE VARCHAR2(100 BYTE) NOT NULL 
, GOODSIMAGE VARCHAR2(500 BYTE) NOT NULL 
, GOODSPRICE NUMBER NOT NULL 
, CHANGE VARCHAR2(100 BYTE) NOT NULL 
, GOODSLOCATION VARCHAR2(200 BYTE) NOT NULL 
, STATUS VARCHAR2(200 BYTE) NOT NULL 
, GOODSINFO VARCHAR2(2000 BYTE) NOT NULL 
, GOODSCOUNT NUMBER NOT NULL 
, LCATEGORY VARCHAR2(100 BYTE) NOT NULL 
, SCATEGORY VARCHAR2(100 BYTE) NOT NULL 
, TAG VARCHAR2(200 BYTE) 
, SAFEPAY VARCHAR2(100 BYTE) 
, DELIVERYPRICE VARCHAR2(200 BYTE) 
, STORENAME VARCHAR2(100 BYTE) NOT NULL 
, T_STATUS VARCHAR2(100 BYTE) 
, CONSTRAINT GOODS_PK PRIMARY KEY 
  (
    GOODSCODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX GOODS_PK ON GOODS (GOODSCODE ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN GOODS.GOODSCODE IS '상품 코드';

COMMENT ON COLUMN GOODS.GOODSTITLE IS '상품 이름';

COMMENT ON COLUMN GOODS.GOODSIMAGE IS '상품 이미지';

COMMENT ON COLUMN GOODS.GOODSPRICE IS '상품 가격';

COMMENT ON COLUMN GOODS.CHANGE IS '교환 여부';

COMMENT ON COLUMN GOODS.GOODSLOCATION IS '거래지역';

COMMENT ON COLUMN GOODS.STATUS IS '상품 상태';

COMMENT ON COLUMN GOODS.GOODSINFO IS '상품 설명';

COMMENT ON COLUMN GOODS.GOODSCOUNT IS '상품 수량';

COMMENT ON COLUMN GOODS.LCATEGORY IS '대분류 카테고리';

COMMENT ON COLUMN GOODS.SCATEGORY IS '소분류 카테고리';

COMMENT ON COLUMN GOODS.TAG IS '연관태그';

COMMENT ON COLUMN GOODS.SAFEPAY IS '안전페이 여부';

COMMENT ON COLUMN GOODS.DELIVERYPRICE IS '배송비 포함 여부';

COMMENT ON COLUMN GOODS.STORENAME IS '상점이름';

COMMENT ON COLUMN GOODS.T_STATUS IS '상품 판매상태';
