CREATE TABLE BUNGAEIMAGE 
(
  IMAGEFILENO NUMBER(10, 0) NOT NULL 
, IMAGEFILENAME VARCHAR2(500 BYTE) NOT NULL 
, IMGDATE DATE DEFAULT sysdate 
, GOODSCODE VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT BUNGAEIMAGE_PK PRIMARY KEY 
  (
    IMAGEFILENO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BUNGAEIMAGE_PK ON BUNGAEIMAGE (IMAGEFILENO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN BUNGAEIMAGE.IMAGEFILENO IS '이미지 파일 넘버';

COMMENT ON COLUMN BUNGAEIMAGE.IMAGEFILENAME IS '이미지 이름';

COMMENT ON COLUMN BUNGAEIMAGE.IMGDATE IS '이미지 등록 날짜';

COMMENT ON COLUMN BUNGAEIMAGE.GOODSCODE IS '상품 코드';
