CREATE TABLE MEMBER 
(
  NAME VARCHAR2(100 BYTE) 
, PHONE VARCHAR2(100 BYTE) 
, ID VARCHAR2(100 BYTE) 
, PW VARCHAR2(100 BYTE) 
, BIRTH VARCHAR2(100 BYTE) 
, NUMBERSALE VARCHAR2(100 BYTE) 
, JOINDATE DATE DEFAULT sysdate 
, VISITSTORE VARCHAR2(100 BYTE) 
, STOREINTRO VARCHAR2(2000 BYTE) 
, STOREIMAGE VARCHAR2(500 BYTE) 
, STORENAME VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT MEMBER_PK PRIMARY KEY 
  (
    STORENAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MEMBER_PK ON MEMBER (STORENAME ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN MEMBER.NAME IS '회원이름';

COMMENT ON COLUMN MEMBER.PHONE IS '회원 전화번호';

COMMENT ON COLUMN MEMBER.ID IS '회원 sns아이디';

COMMENT ON COLUMN MEMBER.PW IS '패스워드';

COMMENT ON COLUMN MEMBER.BIRTH IS '생년월일';

COMMENT ON COLUMN MEMBER.NUMBERSALE IS '판매횟수';

COMMENT ON COLUMN MEMBER.JOINDATE IS '가입일';

COMMENT ON COLUMN MEMBER.VISITSTORE IS '방문자수';

COMMENT ON COLUMN MEMBER.STOREINTRO IS '상점소개글';

COMMENT ON COLUMN MEMBER.STOREIMAGE IS '상점대표이미지';

COMMENT ON COLUMN MEMBER.STORENAME IS '상점명';
