CREATE TABLE MOST_QNA 
(
  M_NUM NUMBER NOT NULL 
, M_HEAD VARCHAR2(200) NOT NULL 
, M_TITLE VARCHAR2(200) NOT NULL 
, M_IMAGE VARCHAR2(200) NOT NULL 
, M_CONTENT VARCHAR2(1000) NOT NULL 
, CONSTRAINT MOST_QNA_PK PRIMARY KEY 
  (
    M_NUM 
  )
  ENABLE 
);

COMMENT ON COLUMN MOST_QNA.M_NUM IS '게시글번호';

COMMENT ON COLUMN MOST_QNA.M_HEAD IS '대분류';

COMMENT ON COLUMN MOST_QNA.M_TITLE IS '제목';

COMMENT ON COLUMN MOST_QNA.M_IMAGE IS '이미지';

COMMENT ON COLUMN MOST_QNA.M_CONTENT IS '내용';
