CREATE TABLE NOTICE 
(
  N_DATE DATE DEFAULT sysdate NOT NULL 
, N_NUM NUMBER NOT NULL 
, N_HEAD VARCHAR2(20) NOT NULL 
, N_TITLE VARCHAR2(20) NOT NULL 
, N_CONTENT VARCHAR2(20) NOT NULL 
, N_IMAGE VARCHAR2(20) 
, CONSTRAINT NOTICE_PK PRIMARY KEY 
  (
    N_NUM 
  )
  ENABLE 
);

COMMENT ON COLUMN NOTICE.N_DATE IS '공지글 등록날짜';

COMMENT ON COLUMN NOTICE.N_NUM IS '공지글 번호';

COMMENT ON COLUMN NOTICE.N_HEAD IS '대분류';

COMMENT ON COLUMN NOTICE.N_TITLE IS '제목';

COMMENT ON COLUMN NOTICE.N_CONTENT IS '내용';

COMMENT ON COLUMN NOTICE.N_IMAGE IS '이미지';
