CREATE TABLE ORDERSHEET 
(
  GOODSCODE VARCHAR2(200) 
, STORENAME VARCHAR2(500) 
, ORDERNUM NUMBER 
, ORDERDATE DATE DEFAULT sysdate 
, ADDRESS VARCHAR2(500) NOT NULL 
, DETAILADDRESS VARCHAR2(500) 
);

COMMENT ON COLUMN ORDERSHEET.GOODSCODE IS '상품코드';

COMMENT ON COLUMN ORDERSHEET.STORENAME IS '상점이름';

COMMENT ON COLUMN ORDERSHEET.ORDERNUM IS '주문번호';

COMMENT ON COLUMN ORDERSHEET.ORDERDATE IS '주문일자';

COMMENT ON COLUMN ORDERSHEET.ADDRESS IS '주소';

COMMENT ON COLUMN ORDERSHEET.DETAILADDRESS IS '상세주소';
