CREATE TABLE QNA 
(
  STORENAME VARCHAR2(200) NOT NULL 
, Q_NUM VARCHAR2(20) NOT NULL 
, Q_HEAD VARCHAR2(100) NOT NULL 
, Q_SUBHEAD VARCHAR2(100) NOT NULL 
, Q_SELECTTITLE VARCHAR2(100) NOT NULL 
, COLUMN6 VARCHAR2(1000) NOT NULL 
, Q_IMAGE VARCHAR2(200) 
);

COMMENT ON COLUMN QNA.STORENAME IS '상점명';

COMMENT ON COLUMN QNA.Q_NUM IS '게시글 번호';

COMMENT ON COLUMN QNA.Q_HEAD IS '대분류';

COMMENT ON COLUMN QNA.Q_SUBHEAD IS '소분류';

COMMENT ON COLUMN QNA.Q_SELECTTITLE IS '제목선택';

COMMENT ON COLUMN QNA.COLUMN6 IS '내용';

COMMENT ON COLUMN QNA.Q_IMAGE IS '이미지';
