CREATE TABLE REVIEW 
(
  WRITERNAME VARCHAR2(200) NOT NULL 
, STORENAME VARCHAR2(200) NOT NULL 
, GOODSTITLE VARCHAR2(200) NOT NULL 
, REVIEWSTAR VARCHAR2(20) NOT NULL 
, REVIEWCONTENTS VARCHAR2(200) NOT NULL 
, REVIEWIMAGE VARCHAR2(200) 
, REVIEWDATE DATE DEFAULT sysdate 
);

COMMENT ON COLUMN REVIEW.WRITERNAME IS '글쓴이';

COMMENT ON COLUMN REVIEW.STORENAME IS '상품구매한 상점이름';

COMMENT ON COLUMN REVIEW.GOODSTITLE IS '상품명';

COMMENT ON COLUMN REVIEW.REVIEWSTAR IS '별점';

COMMENT ON COLUMN REVIEW.REVIEWCONTENTS IS '후기내용';

COMMENT ON COLUMN REVIEW.REVIEWIMAGE IS '후기 이미지';

COMMENT ON COLUMN REVIEW.REVIEWDATE IS '작성날짜';
